displayName=Better Item Identification
author=Hotdogwaterguy
description=A version with expanded options for item identification
tags=item, identification, labels, abbreviations, seeds, herbs, saplings, seedlings, unfinished, potions
version=
plugins=com.betteritemidentification.BetterItemIdentificationPlugin
build=standard